engines:
  rubocop:
    enabled: true
    #checks:
    # Rubocop/Metrics/ClassLength:
    #   enabled: false
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
      - 46375a445c03d8e1e8b9508f1be2b341
      - 205ba2a7d2fab138d90bfc4310549c66
      - 5e98926627c19c41b3b10b1e8a460d58
    config:
      languages:
      - ruby
        #mass_threshold: 30
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
- Gemfile.lock
