# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
require 'faker'

if User.all.empty?
  User.create(email: 'rodrigovdb@gmail.com', password: 'rapadura')
end

if Band.count.zero?
  user = User.first

  2.times do
    band = Band.create(name: Faker::Movies::HitchhikersGuideToTheGalaxy.starship, owner: user)
    BandUser.create(user: user, band: band)
  end
end

if Song.count.zero?
  Band.all.each do |band|
    [1,3].sample.times.each do
      setlist = Setlist.create(
        band: band,
        name: Faker::Movies::HitchhikersGuideToTheGalaxy.planet,
        date: Faker::Date.forward(days: 60),
        notes: 'Auto Generated by seeds'
      )

      [3, 5].sample.times do |item|
        song = Song.create(
          band: band,
          name: Faker::Movies::HitchhikersGuideToTheGalaxy.location,
          artist: Faker::Movies::HitchhikersGuideToTheGalaxy.specie,
          key: Faker::Music.key,
          duration: [1, 1.5, 2, 2.5, 3, 3.5].sample.minutes,
          chords: Faker::Movies::HitchhikersGuideToTheGalaxy.quote
        )

        SetlistSong.create(setlist: setlist, song: song, display_sort: item)
      end
    end

    2.times.each do
      song = Song.create(
        band: band,
        name: Faker::Movies::HitchhikersGuideToTheGalaxy.location,
        artist: Faker::Movies::HitchhikersGuideToTheGalaxy.specie,
        key: Faker::Music.key,
        duration: [1, 1.5, 2, 2.5, 3, 3.5].sample.minutes,
        chords: Faker::Movies::HitchhikersGuideToTheGalaxy.quote
      )

      band.reload.setlists.each do |setlist|
        item = setlist.setlist_songs.map(&:display_sort).max

        SetlistSong.create(setlist: setlist, song: song, display_sort: item)
      end
    end
  end
end
